Repository sonia-auv/sonia-deploy, pull requests merged in 2021-11, with the labels that each got.

#13 Fix/test piscine
  docker-compose.auv8.yml
  docker-compose.local.yml
Labels: Priority: Low, Type: Feature

#16 Feature/behaviors
  docker-compose.auv8.yml
Labels: Priority: High, Type: Bug

#15 Feature/io testing
  docker-compose.auv8.yml
  docker-compose.local.yml
  launch_local.sh
  pull_local.sh
Labels: Priority: High, Type: Feature
