Repository sonia-auv/sonia-deploy, pull requests merged in 2021-09, with the labels that each got.

#8 Feature/add telemetry
  docker-compose.auv8.yml
  docker-compose.local.yml
Labels: Priority: Critical, Type: Enhancement

#10 Feature/power testing
  docker-compose.auv8.yml
Labels: Priority: High, Type: Bug

#11 Feature/provider system
  docker-compose.auv7.yml
  docker-compose.auv8.yml
  docker-compose.local.yml
  launch_auv8.sh
  launch_local.sh
  pull_auv8.sh
  pull_local.sh
  token.txt
Labels: Priority: Medium, Type: Enhancement
